Update check

diff --git a/.github/workflows/block-quality-check.yml b/.github/workflows/block-quality-check.yml
--- a/.github/workflows/block-quality-check.yml
+++ b/.github/workflows/block-quality-check.yml
@@ -39,10 +39,13 @@ jobs:
         run: poetry run python3 fjblock.py sync
 
       - name: Check if everything is in sync
-        id: changed-files
-        uses: tj-actions/changed-files@v39
-        with:
-          fail_on_initial_diff_error: true
+        run: |
+          if git diff --quiet; then
+            echo "No changes found, we are good to go!"
+          else
+            echo "Error: Changes detected. Please make sure to run the sync command and commit the changes"
+            exit 1
+          fi
 
   block-code-style-check:
     runs-on: ubuntu-latest
